const fs = require('node:fs')
const path = require('node:path')
const sharp = require('sharp')
const workspace = path.resolve(__dirname, '../../..')
const destination = path.join(workspace, 'webmobile/assets/contract-confirmation-banner.png')
async function main() {
  fs.mkdirSync(path.dirname(destination), { recursive: true })
  // Copy the existing Electron brand pixels; ImageGen never recreates the logo.
  const logo = await sharp(path.join(workspace, 'src/renderer/src/assets/an_khang_home_logo_ngang.png')).flatten({ background: '#ffffff' }).resize(324, 108).extend({ top: 10, bottom: 10, left: 14, right: 14, background: '#ffffff' }).png().toBuffer()
  await sharp(path.join(__dirname, 'banner-art.png')).composite([{ input: logo, left: 70, top: 46 }]).png({ palette: true, quality: 95, colours: 256, dither: 0.3 }).toFile(destination)
  const encoded = fs.readFileSync(destination).toString('base64')
  fs.writeFileSync(path.join(workspace, 'src/shared/contract-email-assets.ts'), `// Generated by webmobile/design-references/contract-confirmation-email-20261007/package-assets.cjs.\n// Banner contains the original Electron brand asset, composited without AI redraw.\nimport { CONTRACT_BANNER_CID } from './contract-email-template'\nexport const contractEmailAssets = { contractBanner: { cid: CONTRACT_BANNER_CID, base64: '${encoded}' } }\nexport function contractEmailPreviewHtml(html: string): string {\n  return html.replaceAll('cid:' + CONTRACT_BANNER_CID, 'data:image/png;base64,' + contractEmailAssets.contractBanner.base64)\n}\n`)
  console.log(destination)
  console.log(`Banner bytes: ${fs.statSync(destination).size}`)
}
main().catch(error => { console.error(error.message); process.exitCode = 1 })
